### ISSUE TITLE
Add newsletter

### ISSUE THREAD

**Issue by jonmagic** [CoderDojoGitHub/our-dojo#11]
Once #10 is shipped I would like to add an All Event Newsletter that people can subscribe to in order to get open registration notifications for all new events, rather than having to subscribe to a specific event.

**Comment by mikefowler** [comment]
@jonmagic does the addition of the Mailchimp integration close this issue or are there further features we can implement regarding the newsletter?

**Comment by jonmagic** [comment]
We just need to setup a mailchimp account, a mailing list, and then set the api key in the heroku env.

**Comment by mikefowler** [comment]
We have a Mailchimp account with a mailing list already that I've been using the past few months. Check the admin repo wiki.

**Comment by jonmagic** [comment]
:ship:
