### ISSUE TITLE
Event pre-reqs

### ISSUE THREAD

**Issue by brntbeer** [CoderDojoGitHub/our-dojo#15]
I think to attend a session we should at least list some suggested pre-reqs.

Some of these had been collected from other ... sansei? 
## Pre-reqs
- Typing into a text editor
- Able to open a text editor
- Knowing how to create new files and save files
- copy and pasting

(Possibly a parent could help them with this stuff)

Think this could go under some FAQ section and was almost thinking about this being able to be included in an intro email. Thoughts on that?

**Comment by KartikTalwar** [comment]
@brntbeer Maybe just have this data on a FAQ (or standalone) page and we can include a link to the page on the email?

```
- Be sure to bring a laptop
- Pack your lunch
- Check you have this software installed
- Know how to do all this
```

**Comment by kneath** [comment]
Windows or Mac!

**Comment by brntbeer** [comment]
haha @KartikTalwar I totally already mentioned a FAQ page!

But yes, those items too would be great to have mentioned, including the windows and mac section

**Comment by jonmagic** [comment]
:ship:
