### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by jonmagic** [CoderDojoGitHub/our-dojo#16]
The [main functionality](https://github.com/CoderDojoSF/event-app/issues/9) is there although a few issues remain: #13 #11 #15 

Those three issues also relate to the design so they should be taken into account while redesigning.

I briefly talked with @nrrrdcore to solicit design help. She asked about deploying so I added her and several other people as collaborators on Heroku. [Instructions for deploying](https://github.com/CoderDojoSF/event-app/blob/master/README.md#deploying) are in the [README](https://github.com/CoderDojoSF/event-app/blob/master/README.md).

**Comment by nrrrdcore** [comment]
So assuming everything in master is deployed to http://coderdojosf.herokuapp.com/ , I have a couple of questions:
- What are the lessons supposed to do? Right now, clicking on them doesn't really do anything. I'd love to understand the flow a little better before I start designin'. 
- How much should this represent GitHub? From a Universe perspective, how much of our brand do we want to bleed into this minisite? Or should we try to give it it's own, very low-maintenance brand/look/feel cc/ @cameronmcefee 
- Is this site just to host the lessons? Where will the scheduled events go? 

Maybe the best idea is to talk in person @jonmagic and maybe do some whiteboarding (?) so I can get the full picture and start knocking this out.

**Comment by jonmagic** [comment]
My bad @nrrrdcore, refresh the site and you'll see it has an event in the future now. Event data is automatically imported along with the lesson and if an upcoming event (or events) exist it will show the next events data along with the lesson. In addition the lesson page reflects the upcoming event and has a signup form.  

You can see all the screenshots I took during development here to show each state https://github.com/CoderDojoSF/event-app/pull/10

**Comment by cameronmcefee** [comment]
@nrrrdcore We intend to try to encourage other dojos to use this app, so we probably shouldn't brand it GitHub style, even with our `<verb> with <3 by GitHub` footer. I'd target the brand more toward CoderDojo (if at all), though they don't really have their own brand to speak of. Honestly, I think you've got room to do whatever you like with it.

About the only stylistic stuff I've done with our dojo was in my [original pitch](https://talks.githubapp.com/talk/1b98ff14ed7c271e84570fd2bbacdb639f396be4) to start it, and even that wasn't particularly exciting. Feel free to do whatever you like, but do so considering that other dojos across the world may use the same site.

**Comment by nrrrdcore** [comment]
@cameronmcefee awesome, thanks so much for explaining!

**Comment by jonmagic** [comment]
:ship:
