### ISSUE TITLE
Enhanced lesson.json

### ISSUE THREAD

**Issue by cameronmcefee** [CoderDojoGitHub/our-dojo#17]
Today I ran into a couple new scenarios we might want to think about for lesson.json. Multipart lessons and url slugs
## Multipart lessons

In https://github.com/CoderDojoSF/build-your-adventure we're storing all 6 lesson parts in one repo. I'm starting to wonder if lesson.json is more of a manifest like a bower or npm package, where we can specify an array of lessons in a "class". Each of those lessons in the json could specify file paths to the readme for the lesson and any relevant data like demo files or completed samples.
## Url slugs

I found myself wondering how an app that uses the GitHub api to create a frontend for our lessons will handle linking between multipart lessons. My guess is that we'd need to give each lesson a url slug that's relative to the main lesson that we can point stuff to.

**Comment by jonmagic** [comment]
Closing in favor of #33
