### ISSUE TITLE
Sending invites.

### ISSUE THREAD

**Issue by jonmagic** [CoderDojoGitHub/our-dojo#2]
On #1 I am trying to automate the process of creating and managing events on Eventbrite. The one thing I haven't figured out with their API is how to send invites out once you create a group of tickets for an event. The sending of invites is something you do through Eventbrite right? Or is it a manual process outside of Eventbrite once you have created the tickets?

Since I'm new to using Eventbrite I was wondering if @cameronmcefee or @brntbeer could peruse the [API docs](http://developer.eventbrite.com/doc/) and see if there is something I am missing?

**Comment by cameronmcefee** [comment]
Right now it's a manual process.

When I first create the event, I set the `sales status` of all tickets to "hidden" so they don't appear on the event page. I have a promo code set up for each ticket that gives me a url I can send to people for advanced notice.

For the earlybird tickets, I send the people that signed up for the previous event the url to the promo code for the student tickets.

On the day that I announce tickets, I switch the sales status of the student tickets to "on sale", and then share the event url across the various media.

**Comment by cameronmcefee** [comment]
My guess is it would be the `hide` property of [`ticket_update`](http://developer.eventbrite.com/doc/tickets/ticket_update/)

**Comment by jonmagic** [comment]
Ok cool, I'm good to go.

**Comment by cameronmcefee** [comment]
As for the promo code, if you're copying the previous event, I'm guessing it's already in there. If you're creating a new event each time, check out [`discounts`](http://developer.eventbrite.com/doc/discounts/). This is what ours looks like from the web UI

![Screen Shot 2013-02-10 at 2 11 53 PM](https://f.cloud.github.com/assets/72919/143855/efd435b2-73ce-11e2-8738-450c276dcfe1.png)
