### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by jonmagic** [CoderDojoGitHub/our-dojo#32]
I'd like to rename the project and repository before too many folks fork and then have to update their forks when we do end up renaming it. Any recommendations for a name? The app basically:
- Is our landing page for students and parents to find out about the where and when of upcoming classes.
- Class registration and newsletters.
- Links to all past lessons.

If you haven't checked it out in the wild visit http://coderdojosf.com

**Comment by cameronmcefee** [comment]
Perhaps we should give it a clear name that is less boring, something like `our-dojo` or `dojo-hq`?

**Comment by mikefowler** [comment]
I like `dojo-hq`, or something similar, letting the description handle the details.

**Comment by KartikTalwar** [comment]
I vote for `our-dojo`. I think `hq` adds a businessy/central appeal to it. Plus our-dojo also would work nicely when forked by others /{location}/our-dojo

**Comment by cameronmcefee** [comment]
> hq adds a businessy/central appeal to it

Yeah, I definitely can agree with that.

**Comment by mikefowler** [comment]
Hmm, I can see that too.

:+1: for `our-dojo`.

**Comment by jonmagic** [comment]
Renamed :+1:
