### ISSUE TITLE
Support other dojo's

### ISSUE THREAD

**Issue by jonmagic** [CoderDojoGitHub/our-dojo#34]
If this application proves useful over the next few months I will feel comfortable encouraging other dojo's to use it. To me success means handling our next series of class registrations that results in less work for the organizer and parents than the alternative (eventbrite).

At that point some infrastructure work will need done to make the home page, location and directions, and other parts of the website dynamic. I propose the next dojo to use it spearheads that effort as they'll have the actual content to drive the design. I'm willing to act as an advisor and pull request reviewer if we get to that stage.

**Comment by marcyDel** [comment]
Our dojo is very interested in testing out your app.  Be happy to give you feedback and see what we can do with it.

Marcy

**Comment by jonmagic** [comment]
@marcyDel awesome! I have read through https://github.com/CoderDojoSF/event-app/issues/24 and these all sound like interesting ideas. I'm not necessarily willing to lead the charge on development though as these are not currently needs in our Dojo, but I'm totally willing to be an advisor and review pull requests.
