### ISSUE TITLE
Add March event to site

### ISSUE THREAD

**Issue by jonmagic** [CoderDojoGitHub/our-dojo#35]
Research what it will take to support an event without a lesson repository and a custom registration size and implement for our March event.

**Comment by jonmagic** [comment]
@mikefowler @jensechu I need the following to start publicizing our March event on the website:
- [x] Title
- [x] Description
- [x] Cover art? Would be super nice to have an image to associate with the event, if no one has any ideas I'll come up with something.

**Comment by jensechu** [comment]
Ah great. I start my new job today, but I can absolutely fill all of this out when I get home around 6:30 if that's not too late. :dancer:

**Comment by mikefowler** [comment]
@jensechu, don't worry about it. I can knock something out this morning, and you can feel free to make edits when you're home tonight.

**Comment by mikefowler** [comment]
@jonmagic, basic details are up in https://github.com/coderdojosf/hour-of-code :+1:

**Comment by jonmagic** [comment]
I logged into the admin section and edited the class_size http://coderdojosf.com/admin/events/6/edit

![edit event coderdojosf__admin](https://f.cloud.github.com/assets/623/2291373/8802836c-a03c-11e3-9c59-21815ab737cb.jpg)
