### ISSUE TITLE
Users are getting registered for wrong event

### ISSUE THREAD

**Issue by jonmagic** [CoderDojoGitHub/our-dojo#47]
For some reason attempting to register for the Hour of Code is actually registering people for the web dev css class.

**Comment by mikefowler** [comment]
Any insight into this? Getting some emails about it, and will let people know they're registered just fine.

**Comment by jonmagic** [comment]
Fixed in https://github.com/CoderDojoSF/our-dojo/commit/016e52e17bd36ed0bf159e849db9fe3129547032

**Comment by jonmagic** [comment]
I fixed all the registrations to be for the correct event as well via the console. Tried doing it from Active Admin but it wasn't working there.

**Comment by mikefowler** [comment]
:+1: deployed?

**Comment by jonmagic** [comment]
Yeah, I've been deploying as soon as I get a fix. Bummed I didn't catch these before but glad I caught it on the first few registrations.
