### ISSUE TITLE
Design and style Event pages.

### ISSUE THREAD

**Issue by jonmagic** [CoderDojoGitHub/our-dojo#5]
- [ ] Event create /events/new
- [ ] Event listings /events
- [ ] Event show /events/:id
- [ ] Event edit /events/:id/edit

/cc @nrrrdcore

**Comment by jonmagic** [comment]
Should probably expose the event state in the UI too and I didn't add a tag for that yet. Possible states:

```

  States = {
    draft: 0,
    event_created: 1,
    invites_sent: 2,
    registration_opened: 3,
    completed: 4,
  }
```

**Comment by jonmagic** [comment]
Once an event has been created on the Eventbrite side we'll have an event id from them and we can provide a link from our event page to theirs, so we'll want to show that link somewhere as well.

**Comment by jonmagic** [comment]
For the customer facing event show page we could use the Eventbrite embeddable thingy if we wanted to.

**Comment by cameronmcefee** [comment]
Yeah, I think using the embedded Evenbrite thing is fine.

**Comment by jonmagic** [comment]
Not relevant anymore.
