### ISSUE TITLE
Releasing registrations?

### ISSUE THREAD

**Issue by mikefowler** [CoderDojoGitHub/our-dojo#52]
What is the proper way to release a registration if we get an email from a parent saying they can no longer make it?

**Comment by jonmagic** [comment]
Just delete it in the app. We don't have a way to notify other registrants at the moment though.

**Comment by mikefowler** [comment]
As it stands, if a registration is deleted in the app, will registration "reopen" immediately on the website, or is that something that happens via an hourly task?

**Comment by jonmagic** [comment]
Immediately.

**Comment by mikefowler** [comment]
:+1: 

One more: what's the difference between `Registrants` and `Registrations`, and does it matter which is deleted?

**Comment by jonmagic** [comment]
So a `Registrant` is just an email address that can have temporary registrations and then actual registrations associated with it. When you sign up for an event it creates the `Registrant` and a `TemporaryRegistration` and after you confirm your email address it converts your `TemporaryRegistration` into a `Registration`. See the `Registrar` documentation for more details https://github.com/CoderDojoSF/our-dojo/blob/master/app/models/registrar.rb
