### ISSUE TITLE
Reusing lesson repositories

### ISSUE THREAD

**Issue by mikefowler** [CoderDojoGitHub/our-dojo#53]
Is it currently (theoretically) possible to simply update the date of an event in ActiveAdmin and thereby essentially "reuse" an event? If not, thoughts?

**Comment by jonmagic** [comment]
I think that would create some weird issues with prior registrations (that are tied to an event). Also makes reporting on the data harder down the road. I think we should create new events, but we can certainly optimize that process.

**Comment by mikefowler** [comment]
New events, but with the same repository in its configuration? That'll work, right?

**Comment by jonmagic** [comment]
> New events, but with the same repository in its configuration? That'll work, right?

That should be fine. In fact, you can just update the lesson.json file in the repository and add a new event to the events array and it will automatically be imported. [For example](https://github.com/CoderDojoSF/hour-of-code/blob/master/lesson.json#L6):

``` json
{
  "title": "Hour of Code",
  "summary": "In this lesson, we'll learn the very basics of programming by exploring Core.org's Hour of Code.",
  "image_url": "https://raw.github.com/CoderDojoSF/hour-of-code/master/cover.jpg",
  "author_github_username": "jensechu",
  "events": [
    {
      "location": "GitHub, 88 Colin P. Kelly Junior St., San Francisco, CA",
      "date": "Sat Mar 15 2014 10:00:00 GMT-0700 (PDT)",
      "length_in_hours": null,
      "teacher_github_username": "jensechu"
    },
    {
      "location": "GitHub, 88 Colin P. Kelly Junior St., San Francisco, CA",
      "date": "Sat Apr 12 2014 10:00:00 GMT-0700 (PDT)",
      "length_in_hours": null,
      "teacher_github_username": "mikefowler"
    }
  ],
  "length": "2"
}
```

**Comment by mikefowler** [comment]
^ that's what I was looking for. That works great, and is actually awesome information to retain anyways, being able to see which days this class has ever been run. :+1:

**Comment by mikefowler** [comment]
@jonmagic: started an [FAQ](https://github.com/CoderDojoSF/our-dojo/wiki) section for storing this kind of stuff. Closing.
