### ISSUE TITLE
Add details to event confirmation emails

### ISSUE THREAD

**Issue by mikefowler** [CoderDojoGitHub/our-dojo#54]
Per feedback of parents from this past event we should consider including:
- the number of students registered
- the location/date/time of the event
- the fact that you don't need to print a ticket, just show up
- reiterate that you need to bring a laptop

Basically, the information that's on the front page of the website, but in email format for people to refer back to.

I'll work on this in the next couple days and send a PR.

**Comment by jonmagic** [comment]
Here is the current email:

![coderdojo - san francisco your reservation is confirmed](https://cloud.githubusercontent.com/assets/623/2755409/f94cf224-c967-11e3-9471-d8e38b8e5c53.jpg)

> the number of students registered

Why would we include the number of registered students in the email to parents?

> the location/date/time of the event

Already on there.

> the fact that you don't need to print a ticket, just show up
> reiterate that you need to bring a laptop

Working on a PR now.
