### ISSUE TITLE
Lesson imported but not event

### ISSUE THREAD

**Issue by mikefowler** [CoderDojoGitHub/our-dojo#56]
For @jonmagic: a `lesson.json` was added to our [binary-code](https://github.com/CoderDojoSF/binary-code) repo, but with malformed JSON (in its original version). Seems like the `Lesson` was imported to ActiveAdmin but not the `Event`. If I delete the lesson, will it automatically re-import the whole shebang next task run?

**Comment by jonmagic** [comment]
I think it should try and re-import the event on each run, so just fixing the json should be good enough, you shouldn't have to delete anything.

**Comment by mikefowler** [comment]
Indeed it was. Closing.
