### ISSUE TITLE
Promo codes don't work

### ISSUE THREAD

**Issue by cameronmcefee** [CoderDojoGitHub/our-dojo#7]
People trying to claim alumni student tickets were unable to do so. Looking into it, it appears that it's not possible to create promo codes for non-hidden tickets. Since the student tickets were visible but set to not appear until the official launch date, they effectively were not given "permission" to have a promo code. Rather than get some sort of error it simply created the promo code with no actual ticket attached (eventbrite's fault).

My suggestion is that the app create the ticket which is purchasable from the time of creation. Then all we do is toggle the visibility of it when it comes time to go public.

**Comment by jonmagic** [comment]
moving away from eventbrite this should be null and void
